### ISSUE TITLE
Swapping order in TUI mismatches rendered preview with actual task

### ISSUE THREAD

**Issue by nicpayne713** [WaylonWalker/markata-todoui#3]
Behavior: When moving task1 below task2 the preview keeps task1's preview when task2 is highlighted and vice versa

**Comment by WaylonWalker** [comment]
I think I need guuid's to keep track of who is who, it seems like things get complex pretty quick to keep the same filters everywhere to make the index line up.

**Comment by WaylonWalker** [comment]
Fixed in #5
