### ISSUE TITLE
Priority ordering can go negative and exceeds number of tasks in a column

### ISSUE THREAD

**Issue by nicpayne713** [WaylonWalker/markata-todoui#8]
When switching task order the priority changes up and down as expected and the tasks reorder based on the priority.

The bus is that I can increase a priority indefinitely either positively or negatively

https://user-images.githubusercontent.com/32268273/168338724-e56c4a22-3209-4b35-a70a-c361f7268e14.mp4

.

**Comment by nicpayne713** [comment]
After doing the indefinite ordering again maybe it's not such a weird thing but idk if it's entirely expected behavior or not

**Comment by WaylonWalker** [comment]
Yep, that is expected.  I am not entirely sure that it should be though. it we capped it at the max, what happens when I edit my frontmatter and make it big?

**Comment by pypeaday** [comment]
hmm... ok I'm not totally sure, cause also then you might think about enforcing a unique priority within any group? That feels like it might be too restrictive... so maybe this expected behavior is just fine. I think this could be closed unless it comes up again
